apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosi-defaultbc-webhook-deployment
  namespace: default
  labels:
    app: working-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: working-test
  template:
    metadata:
      labels:
        app: working-test
    spec:
      containers:
        - name: cosi-defaultbc
          image: cosi-defaultbc:latest
          imagePullPolicy: IfNotPresent
          args:
          - -tlsCertFile=/etc/webhook/certs/cert.pem
          - -tlsKeyFile=/etc/webhook/certs/key.pem
          - -alsologtostderr
          - -v=4
          - 2>&1
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: cosi-defaultbc-webhook-certs
