apiVersion: v1
kind: Service
metadata:
  name: cosi-defaultbc-webhook
  namespace: default
  labels:
    app: working-test
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: working-test

